name: Deploy
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4  # v3 → v4 업데이트
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTO_ACTIONS }}  # 권한 문제 방지
      
      - name: Push to personal repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}"
          
          # 안전한 URL 형식 사용
          git remote add personal https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com/MNA11/team1-fe.git
          
          # force-with-lease 사용 (더 안전)
          git push personal master --force-with-lease